/********************************************************************************
** Form generated from reading UI file 'practice.ui'
**
** Created: Tue Dec 11 13:12:26 2012
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PRACTICE_H
#define UI_PRACTICE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCalendarWidget>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_practiceClass
{
public:
    QAction *actionExit;
    QAction *actionExit_2;
    QAction *action_2;
    QWidget *centralWidget;
    QPushButton *Square1_1;
    QPushButton *Square1_2;
    QPushButton *Square1_4;
    QPushButton *Square1_3;
    QPushButton *Square2_1;
    QPushButton *Square2_2;
    QPushButton *Square2_4;
    QPushButton *Square2_3;
    QPushButton *Square3_1;
    QPushButton *Square3_3;
    QPushButton *Square3_4;
    QPushButton *Square3_2;
    QPushButton *Rec1_1;
    QPushButton *Rec1_3;
    QPushButton *Rec1_5;
    QPushButton *Rec1_7;
    QPushButton *Rec1_9;
    QPushButton *Rec1_11;
    QPushButton *Rec1_2;
    QPushButton *Rec1_4;
    QPushButton *Rec1_6;
    QPushButton *Rec1_8;
    QPushButton *Rec1_10;
    QPushButton *Rec1_12;
    QPushButton *Rec2_1;
    QPushButton *Rec2_3;
    QPushButton *Rec2_5;
    QPushButton *Rec2_11;
    QPushButton *Rec2_9;
    QPushButton *Rec2_7;
    QPushButton *Rec2_10;
    QPushButton *Rec2_8;
    QPushButton *Rec2_6;
    QPushButton *Rec2_4;
    QPushButton *Rec2_2;
    QPushButton *Rec2_12;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QCalendarWidget *calendarWidget;
    QPushButton *Square1_5;
    QPushButton *Square1_6;
    QStatusBar *statusBar;
    QMenuBar *menuBar;
    QMenu *menu;

    void setupUi(QMainWindow *practiceClass)
    {
        if (practiceClass->objectName().isEmpty())
            practiceClass->setObjectName(QString::fromUtf8("practiceClass"));
        practiceClass->resize(1003, 880);
        QFont font;
        font.setPointSize(9);
        practiceClass->setFont(font);
        practiceClass->setStyleSheet(QString::fromUtf8(""));
        actionExit = new QAction(practiceClass);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionExit_2 = new QAction(practiceClass);
        actionExit_2->setObjectName(QString::fromUtf8("actionExit_2"));
        action_2 = new QAction(practiceClass);
        action_2->setObjectName(QString::fromUtf8("action_2"));
        action_2->setCheckable(true);
        centralWidget = new QWidget(practiceClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        Square1_1 = new QPushButton(centralWidget);
        Square1_1->setObjectName(QString::fromUtf8("Square1_1"));
        Square1_1->setGeometry(QRect(140, 100, 71, 61));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Berlin Sans FB Demi"));
        font1.setPointSize(10);
        Square1_1->setFont(font1);
        Square1_1->setCursor(QCursor(Qt::PointingHandCursor));
        Square1_1->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }\n"
""));
        Square1_1->setCheckable(true);
        Square1_2 = new QPushButton(centralWidget);
        Square1_2->setObjectName(QString::fromUtf8("Square1_2"));
        Square1_2->setGeometry(QRect(210, 100, 71, 61));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Berlin Sans FB Demi"));
        font2.setPointSize(10);
        font2.setBold(false);
        font2.setWeight(50);
        Square1_2->setFont(font2);
        Square1_2->setCursor(QCursor(Qt::PointingHandCursor));
        Square1_2->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square1_2->setCheckable(true);
        Square1_4 = new QPushButton(centralWidget);
        Square1_4->setObjectName(QString::fromUtf8("Square1_4"));
        Square1_4->setGeometry(QRect(210, 160, 71, 61));
        Square1_4->setFont(font1);
        Square1_4->setCursor(QCursor(Qt::PointingHandCursor));
        Square1_4->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square1_4->setCheckable(true);
        Square1_3 = new QPushButton(centralWidget);
        Square1_3->setObjectName(QString::fromUtf8("Square1_3"));
        Square1_3->setGeometry(QRect(140, 160, 71, 61));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Berlin Sans FB Demi"));
        font3.setPointSize(10);
        font3.setBold(true);
        font3.setWeight(75);
        Square1_3->setFont(font3);
        Square1_3->setCursor(QCursor(Qt::PointingHandCursor));
        Square1_3->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square1_3->setCheckable(true);
        Square2_1 = new QPushButton(centralWidget);
        Square2_1->setObjectName(QString::fromUtf8("Square2_1"));
        Square2_1->setGeometry(QRect(380, 100, 71, 61));
        Square2_1->setFont(font1);
        Square2_1->setCursor(QCursor(Qt::PointingHandCursor));
        Square2_1->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square2_1->setCheckable(true);
        Square2_2 = new QPushButton(centralWidget);
        Square2_2->setObjectName(QString::fromUtf8("Square2_2"));
        Square2_2->setGeometry(QRect(450, 100, 71, 61));
        Square2_2->setFont(font1);
        Square2_2->setCursor(QCursor(Qt::PointingHandCursor));
        Square2_2->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square2_2->setCheckable(true);
        Square2_4 = new QPushButton(centralWidget);
        Square2_4->setObjectName(QString::fromUtf8("Square2_4"));
        Square2_4->setGeometry(QRect(450, 160, 71, 61));
        Square2_4->setFont(font1);
        Square2_4->setCursor(QCursor(Qt::PointingHandCursor));
        Square2_4->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square2_4->setCheckable(true);
        Square2_3 = new QPushButton(centralWidget);
        Square2_3->setObjectName(QString::fromUtf8("Square2_3"));
        Square2_3->setGeometry(QRect(380, 160, 71, 61));
        Square2_3->setFont(font1);
        Square2_3->setCursor(QCursor(Qt::PointingHandCursor));
        Square2_3->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square2_3->setCheckable(true);
        Square3_1 = new QPushButton(centralWidget);
        Square3_1->setObjectName(QString::fromUtf8("Square3_1"));
        Square3_1->setGeometry(QRect(630, 100, 71, 61));
        Square3_1->setFont(font1);
        Square3_1->setCursor(QCursor(Qt::PointingHandCursor));
        Square3_1->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square3_1->setCheckable(true);
        Square3_3 = new QPushButton(centralWidget);
        Square3_3->setObjectName(QString::fromUtf8("Square3_3"));
        Square3_3->setGeometry(QRect(630, 160, 71, 61));
        Square3_3->setFont(font1);
        Square3_3->setCursor(QCursor(Qt::PointingHandCursor));
        Square3_3->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square3_3->setCheckable(true);
        Square3_4 = new QPushButton(centralWidget);
        Square3_4->setObjectName(QString::fromUtf8("Square3_4"));
        Square3_4->setGeometry(QRect(700, 160, 71, 61));
        Square3_4->setFont(font1);
        Square3_4->setCursor(QCursor(Qt::PointingHandCursor));
        Square3_4->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square3_4->setCheckable(true);
        Square3_2 = new QPushButton(centralWidget);
        Square3_2->setObjectName(QString::fromUtf8("Square3_2"));
        Square3_2->setGeometry(QRect(700, 100, 71, 61));
        Square3_2->setFont(font1);
        Square3_2->setCursor(QCursor(Qt::PointingHandCursor));
        Square3_2->setMouseTracking(false);
        Square3_2->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Square3_2->setCheckable(true);
        Rec1_1 = new QPushButton(centralWidget);
        Rec1_1->setObjectName(QString::fromUtf8("Rec1_1"));
        Rec1_1->setGeometry(QRect(240, 350, 71, 61));
        Rec1_1->setFont(font1);
        Rec1_1->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_1->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_1->setCheckable(true);
        Rec1_3 = new QPushButton(centralWidget);
        Rec1_3->setObjectName(QString::fromUtf8("Rec1_3"));
        Rec1_3->setGeometry(QRect(310, 350, 71, 61));
        Rec1_3->setFont(font1);
        Rec1_3->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_3->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_3->setCheckable(true);
        Rec1_5 = new QPushButton(centralWidget);
        Rec1_5->setObjectName(QString::fromUtf8("Rec1_5"));
        Rec1_5->setGeometry(QRect(380, 350, 71, 61));
        Rec1_5->setFont(font1);
        Rec1_5->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_5->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_5->setCheckable(true);
        Rec1_7 = new QPushButton(centralWidget);
        Rec1_7->setObjectName(QString::fromUtf8("Rec1_7"));
        Rec1_7->setGeometry(QRect(450, 350, 71, 61));
        Rec1_7->setFont(font1);
        Rec1_7->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_7->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_7->setCheckable(true);
        Rec1_9 = new QPushButton(centralWidget);
        Rec1_9->setObjectName(QString::fromUtf8("Rec1_9"));
        Rec1_9->setGeometry(QRect(520, 350, 71, 61));
        Rec1_9->setFont(font1);
        Rec1_9->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_9->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_9->setCheckable(true);
        Rec1_11 = new QPushButton(centralWidget);
        Rec1_11->setObjectName(QString::fromUtf8("Rec1_11"));
        Rec1_11->setGeometry(QRect(590, 350, 71, 61));
        Rec1_11->setFont(font1);
        Rec1_11->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_11->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_11->setCheckable(true);
        Rec1_2 = new QPushButton(centralWidget);
        Rec1_2->setObjectName(QString::fromUtf8("Rec1_2"));
        Rec1_2->setGeometry(QRect(240, 410, 71, 61));
        Rec1_2->setFont(font1);
        Rec1_2->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_2->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_2->setCheckable(true);
        Rec1_4 = new QPushButton(centralWidget);
        Rec1_4->setObjectName(QString::fromUtf8("Rec1_4"));
        Rec1_4->setGeometry(QRect(310, 410, 71, 61));
        Rec1_4->setFont(font1);
        Rec1_4->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_4->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_4->setCheckable(true);
        Rec1_6 = new QPushButton(centralWidget);
        Rec1_6->setObjectName(QString::fromUtf8("Rec1_6"));
        Rec1_6->setGeometry(QRect(380, 410, 71, 61));
        Rec1_6->setFont(font1);
        Rec1_6->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_6->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_6->setCheckable(true);
        Rec1_8 = new QPushButton(centralWidget);
        Rec1_8->setObjectName(QString::fromUtf8("Rec1_8"));
        Rec1_8->setGeometry(QRect(450, 410, 71, 61));
        Rec1_8->setFont(font1);
        Rec1_8->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_8->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_8->setCheckable(true);
        Rec1_10 = new QPushButton(centralWidget);
        Rec1_10->setObjectName(QString::fromUtf8("Rec1_10"));
        Rec1_10->setGeometry(QRect(520, 410, 71, 61));
        Rec1_10->setFont(font1);
        Rec1_10->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_10->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_10->setCheckable(true);
        Rec1_12 = new QPushButton(centralWidget);
        Rec1_12->setObjectName(QString::fromUtf8("Rec1_12"));
        Rec1_12->setGeometry(QRect(590, 410, 71, 61));
        Rec1_12->setFont(font1);
        Rec1_12->setCursor(QCursor(Qt::PointingHandCursor));
        Rec1_12->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec1_12->setCheckable(true);
        Rec2_1 = new QPushButton(centralWidget);
        Rec2_1->setObjectName(QString::fromUtf8("Rec2_1"));
        Rec2_1->setGeometry(QRect(240, 550, 71, 61));
        Rec2_1->setFont(font1);
        Rec2_1->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_1->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_1->setCheckable(true);
        Rec2_3 = new QPushButton(centralWidget);
        Rec2_3->setObjectName(QString::fromUtf8("Rec2_3"));
        Rec2_3->setGeometry(QRect(310, 550, 71, 61));
        Rec2_3->setFont(font1);
        Rec2_3->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_3->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_3->setCheckable(true);
        Rec2_5 = new QPushButton(centralWidget);
        Rec2_5->setObjectName(QString::fromUtf8("Rec2_5"));
        Rec2_5->setGeometry(QRect(380, 550, 71, 61));
        Rec2_5->setFont(font1);
        Rec2_5->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_5->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_5->setCheckable(true);
        Rec2_11 = new QPushButton(centralWidget);
        Rec2_11->setObjectName(QString::fromUtf8("Rec2_11"));
        Rec2_11->setGeometry(QRect(590, 550, 71, 61));
        Rec2_11->setFont(font1);
        Rec2_11->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_11->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_11->setCheckable(true);
        Rec2_9 = new QPushButton(centralWidget);
        Rec2_9->setObjectName(QString::fromUtf8("Rec2_9"));
        Rec2_9->setGeometry(QRect(520, 550, 71, 61));
        Rec2_9->setFont(font1);
        Rec2_9->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_9->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_9->setCheckable(true);
        Rec2_7 = new QPushButton(centralWidget);
        Rec2_7->setObjectName(QString::fromUtf8("Rec2_7"));
        Rec2_7->setGeometry(QRect(450, 550, 71, 61));
        Rec2_7->setFont(font1);
        Rec2_7->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_7->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_7->setCheckable(true);
        Rec2_10 = new QPushButton(centralWidget);
        Rec2_10->setObjectName(QString::fromUtf8("Rec2_10"));
        Rec2_10->setGeometry(QRect(520, 610, 71, 61));
        Rec2_10->setFont(font1);
        Rec2_10->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_10->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_10->setCheckable(true);
        Rec2_8 = new QPushButton(centralWidget);
        Rec2_8->setObjectName(QString::fromUtf8("Rec2_8"));
        Rec2_8->setGeometry(QRect(450, 610, 71, 61));
        Rec2_8->setFont(font1);
        Rec2_8->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_8->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_8->setCheckable(true);
        Rec2_6 = new QPushButton(centralWidget);
        Rec2_6->setObjectName(QString::fromUtf8("Rec2_6"));
        Rec2_6->setGeometry(QRect(380, 610, 71, 61));
        Rec2_6->setFont(font1);
        Rec2_6->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_6->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_6->setCheckable(true);
        Rec2_4 = new QPushButton(centralWidget);
        Rec2_4->setObjectName(QString::fromUtf8("Rec2_4"));
        Rec2_4->setGeometry(QRect(310, 610, 71, 61));
        Rec2_4->setFont(font1);
        Rec2_4->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_4->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_4->setCheckable(true);
        Rec2_2 = new QPushButton(centralWidget);
        Rec2_2->setObjectName(QString::fromUtf8("Rec2_2"));
        Rec2_2->setGeometry(QRect(240, 610, 71, 61));
        Rec2_2->setFont(font1);
        Rec2_2->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_2->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_2->setCheckable(true);
        Rec2_12 = new QPushButton(centralWidget);
        Rec2_12->setObjectName(QString::fromUtf8("Rec2_12"));
        Rec2_12->setGeometry(QRect(590, 610, 71, 61));
        Rec2_12->setFont(font1);
        Rec2_12->setCursor(QCursor(Qt::PointingHandCursor));
        Rec2_12->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: rgb(102, 176, 54) }"));
        Rec2_12->setCheckable(true);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(480, 770, 91, 71));
        QFont font4;
        font4.setPointSize(14);
        pushButton->setFont(font4);
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(390, 770, 91, 71));
        pushButton_2->setFont(font4);
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(210, 770, 91, 71));
        pushButton_3->setFont(font4);
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(300, 770, 91, 71));
        pushButton_4->setFont(font4);
        pushButton_6 = new QPushButton(centralWidget);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(120, 770, 91, 71));
        pushButton_6->setFont(font4);
        pushButton_7 = new QPushButton(centralWidget);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(570, 770, 91, 71));
        pushButton_7->setFont(font4);
        pushButton_8 = new QPushButton(centralWidget);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(660, 770, 91, 71));
        pushButton_8->setFont(font4);
        pushButton_9 = new QPushButton(centralWidget);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(750, 770, 91, 71));
        pushButton_9->setFont(font4);
        calendarWidget = new QCalendarWidget(centralWidget);
        calendarWidget->setObjectName(QString::fromUtf8("calendarWidget"));
        calendarWidget->setGeometry(QRect(820, 0, 168, 155));
        Square1_5 = new QPushButton(centralWidget);
        Square1_5->setObjectName(QString::fromUtf8("Square1_5"));
        Square1_5->setGeometry(QRect(980, 840, 16, 16));
        Square1_5->setFont(font3);
        Square1_5->setCursor(QCursor(Qt::PointingHandCursor));
        Square1_5->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: white }"));
        Square1_5->setCheckable(true);
        Square1_6 = new QPushButton(centralWidget);
        Square1_6->setObjectName(QString::fromUtf8("Square1_6"));
        Square1_6->setGeometry(QRect(990, 820, 16, 16));
        Square1_6->setFont(font3);
        Square1_6->setCursor(QCursor(Qt::PointingHandCursor));
        Square1_6->setStyleSheet(QString::fromUtf8("QPushButton { color: white; background-color: white }"));
        Square1_6->setCheckable(true);
        practiceClass->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(practiceClass);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        practiceClass->setStatusBar(statusBar);
        menuBar = new QMenuBar(practiceClass);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1003, 21));
        menu = new QMenu(menuBar);
        menu->setObjectName(QString::fromUtf8("menu"));
        practiceClass->setMenuBar(menuBar);
        QWidget::setTabOrder(Square1_1, Square1_2);
        QWidget::setTabOrder(Square1_2, Square1_3);
        QWidget::setTabOrder(Square1_3, Square1_4);
        QWidget::setTabOrder(Square1_4, Square2_1);
        QWidget::setTabOrder(Square2_1, Square2_2);
        QWidget::setTabOrder(Square2_2, Square2_4);
        QWidget::setTabOrder(Square2_4, Square2_3);
        QWidget::setTabOrder(Square2_3, Square3_1);
        QWidget::setTabOrder(Square3_1, Square3_3);
        QWidget::setTabOrder(Square3_3, Square3_4);
        QWidget::setTabOrder(Square3_4, Square3_2);
        QWidget::setTabOrder(Square3_2, Rec1_1);
        QWidget::setTabOrder(Rec1_1, Rec1_3);
        QWidget::setTabOrder(Rec1_3, Rec1_5);
        QWidget::setTabOrder(Rec1_5, Rec1_7);
        QWidget::setTabOrder(Rec1_7, Rec1_9);
        QWidget::setTabOrder(Rec1_9, Rec1_11);
        QWidget::setTabOrder(Rec1_11, Rec1_2);
        QWidget::setTabOrder(Rec1_2, Rec1_4);
        QWidget::setTabOrder(Rec1_4, Rec1_6);
        QWidget::setTabOrder(Rec1_6, Rec1_8);
        QWidget::setTabOrder(Rec1_8, Rec1_10);
        QWidget::setTabOrder(Rec1_10, Rec1_12);
        QWidget::setTabOrder(Rec1_12, Rec2_1);
        QWidget::setTabOrder(Rec2_1, Rec2_3);
        QWidget::setTabOrder(Rec2_3, Rec2_5);
        QWidget::setTabOrder(Rec2_5, Rec2_11);
        QWidget::setTabOrder(Rec2_11, Rec2_9);
        QWidget::setTabOrder(Rec2_9, Rec2_7);
        QWidget::setTabOrder(Rec2_7, Rec2_10);
        QWidget::setTabOrder(Rec2_10, Rec2_8);
        QWidget::setTabOrder(Rec2_8, Rec2_6);
        QWidget::setTabOrder(Rec2_6, Rec2_4);
        QWidget::setTabOrder(Rec2_4, Rec2_2);
        QWidget::setTabOrder(Rec2_2, Rec2_12);

        menuBar->addAction(menu->menuAction());
        menu->addAction(action_2);
        menu->addAction(actionExit_2);

        retranslateUi(practiceClass);
        QObject::connect(Square1_3, SIGNAL(clicked()), practiceClass, SLOT(clickSquare1_3()));
        QObject::connect(Square2_1, SIGNAL(clicked()), practiceClass, SLOT(clickSquare2_1()));
        QObject::connect(Square2_2, SIGNAL(clicked()), practiceClass, SLOT(clickSquare2_2()));
        QObject::connect(Square2_3, SIGNAL(clicked()), practiceClass, SLOT(clickSquare2_3()));
        QObject::connect(Square2_4, SIGNAL(clicked()), practiceClass, SLOT(clickSquare2_4()));
        QObject::connect(Square3_1, SIGNAL(clicked()), practiceClass, SLOT(clickSquare3_1()));
        QObject::connect(Square3_2, SIGNAL(clicked()), practiceClass, SLOT(clickSquare3_2()));
        QObject::connect(Square3_3, SIGNAL(clicked()), practiceClass, SLOT(clickSquare3_3()));
        QObject::connect(Square3_4, SIGNAL(clicked()), practiceClass, SLOT(clickSquare3_4()));
        QObject::connect(Rec1_2, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_2()));
        QObject::connect(Square1_1, SIGNAL(clicked()), practiceClass, SLOT(clickSquare4_1()));
        QObject::connect(Square1_2, SIGNAL(clicked()), practiceClass, SLOT(clickSqaure1_2()));
        QObject::connect(Rec1_1, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_1()));
        QObject::connect(Rec1_4, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_4()));
        QObject::connect(Rec1_3, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_3()));
        QObject::connect(Rec1_5, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_5()));
        QObject::connect(Rec1_6, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_6()));
        QObject::connect(Rec1_7, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_7()));
        QObject::connect(Rec1_8, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_8()));
        QObject::connect(Rec1_9, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_9()));
        QObject::connect(Rec1_10, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_10()));
        QObject::connect(Rec1_11, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_11()));
        QObject::connect(Rec1_12, SIGNAL(clicked()), practiceClass, SLOT(clickRec1_12()));
        QObject::connect(Rec2_1, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_1()));
        QObject::connect(Rec2_2, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_2()));
        QObject::connect(Rec2_3, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_3()));
        QObject::connect(Rec2_4, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_4()));
        QObject::connect(Rec2_5, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_5()));
        QObject::connect(Rec2_6, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_6()));
        QObject::connect(Rec2_7, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_7()));
        QObject::connect(Rec2_8, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_8()));
        QObject::connect(Rec2_9, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_9()));
        QObject::connect(Rec2_10, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_10()));
        QObject::connect(Rec2_11, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_11()));
        QObject::connect(Rec2_12, SIGNAL(clicked()), practiceClass, SLOT(clickRec2_12()));
        QObject::connect(Square1_4, SIGNAL(clicked()), practiceClass, SLOT(clickSquare1_4()));
        QObject::connect(pushButton_6, SIGNAL(clicked()), practiceClass, SLOT(input1()));
        QObject::connect(pushButton_3, SIGNAL(clicked()), practiceClass, SLOT(input2()));
        QObject::connect(pushButton_4, SIGNAL(clicked()), practiceClass, SLOT(input3()));
        QObject::connect(pushButton_2, SIGNAL(clicked()), practiceClass, SLOT(input4()));
        QObject::connect(pushButton, SIGNAL(clicked()), practiceClass, SLOT(input5()));
        QObject::connect(pushButton_7, SIGNAL(clicked()), practiceClass, SLOT(input6()));
        QObject::connect(pushButton_8, SIGNAL(clicked()), practiceClass, SLOT(input7()));
        QObject::connect(pushButton_9, SIGNAL(clicked()), practiceClass, SLOT(input8()));
        QObject::connect(Square1_2, SIGNAL(clicked()), practiceClass, SLOT(clickSquare4_2()));
        QObject::connect(Square1_6, SIGNAL(clicked()), practiceClass, SLOT(clickSqaure1_1()));
        QObject::connect(Square1_5, SIGNAL(clicked()), practiceClass, SLOT(clickSqaure1_2()));

        QMetaObject::connectSlotsByName(practiceClass);
    } // setupUi

    void retranslateUi(QMainWindow *practiceClass)
    {
        practiceClass->setWindowTitle(QApplication::translate("practiceClass", "practice", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("practiceClass", "Exit", 0, QApplication::UnicodeUTF8));
        actionExit_2->setText(QApplication::translate("practiceClass", "Exit", 0, QApplication::UnicodeUTF8));
        action_2->setText(QApplication::translate("practiceClass", "\354\236\254\353\260\260\354\271\230", 0, QApplication::UnicodeUTF8));
        Square1_1->setText(QApplication::translate("practiceClass", "Square1_1", 0, QApplication::UnicodeUTF8));
        Square1_2->setText(QApplication::translate("practiceClass", "Sqaure1_2", 0, QApplication::UnicodeUTF8));
        Square1_4->setText(QApplication::translate("practiceClass", "Sqaure1_4", 0, QApplication::UnicodeUTF8));
        Square1_3->setText(QApplication::translate("practiceClass", "Sqaure1_3", 0, QApplication::UnicodeUTF8));
        Square2_1->setText(QApplication::translate("practiceClass", "Square2_1", 0, QApplication::UnicodeUTF8));
        Square2_2->setText(QApplication::translate("practiceClass", "Square2_2", 0, QApplication::UnicodeUTF8));
        Square2_4->setText(QApplication::translate("practiceClass", "Square2_4", 0, QApplication::UnicodeUTF8));
        Square2_3->setText(QApplication::translate("practiceClass", "Square2_3", 0, QApplication::UnicodeUTF8));
        Square3_1->setText(QApplication::translate("practiceClass", "Square3_1", 0, QApplication::UnicodeUTF8));
        Square3_3->setText(QApplication::translate("practiceClass", "Square3_3", 0, QApplication::UnicodeUTF8));
        Square3_4->setText(QApplication::translate("practiceClass", "Square3_4", 0, QApplication::UnicodeUTF8));
        Square3_2->setText(QApplication::translate("practiceClass", "Square3_2", 0, QApplication::UnicodeUTF8));
        Rec1_1->setText(QApplication::translate("practiceClass", "Rec1_1", 0, QApplication::UnicodeUTF8));
        Rec1_3->setText(QApplication::translate("practiceClass", "Rec1_3", 0, QApplication::UnicodeUTF8));
        Rec1_5->setText(QApplication::translate("practiceClass", "Rec1_5", 0, QApplication::UnicodeUTF8));
        Rec1_7->setText(QApplication::translate("practiceClass", "Rec1_7", 0, QApplication::UnicodeUTF8));
        Rec1_9->setText(QApplication::translate("practiceClass", "Rec1_9", 0, QApplication::UnicodeUTF8));
        Rec1_11->setText(QApplication::translate("practiceClass", "Rec1_11", 0, QApplication::UnicodeUTF8));
        Rec1_2->setText(QApplication::translate("practiceClass", "Rec1_2", 0, QApplication::UnicodeUTF8));
        Rec1_4->setText(QApplication::translate("practiceClass", "Rec1_4", 0, QApplication::UnicodeUTF8));
        Rec1_6->setText(QApplication::translate("practiceClass", "Rec1_6", 0, QApplication::UnicodeUTF8));
        Rec1_8->setText(QApplication::translate("practiceClass", "Rec1_8", 0, QApplication::UnicodeUTF8));
        Rec1_10->setText(QApplication::translate("practiceClass", "Rec1_10", 0, QApplication::UnicodeUTF8));
        Rec1_12->setText(QApplication::translate("practiceClass", "Rec1_12", 0, QApplication::UnicodeUTF8));
        Rec2_1->setText(QApplication::translate("practiceClass", "Rec2_1", 0, QApplication::UnicodeUTF8));
        Rec2_3->setText(QApplication::translate("practiceClass", "Rec2_3", 0, QApplication::UnicodeUTF8));
        Rec2_5->setText(QApplication::translate("practiceClass", "Rec2_5", 0, QApplication::UnicodeUTF8));
        Rec2_11->setText(QApplication::translate("practiceClass", "Rec2_11", 0, QApplication::UnicodeUTF8));
        Rec2_9->setText(QApplication::translate("practiceClass", "Rec2_9", 0, QApplication::UnicodeUTF8));
        Rec2_7->setText(QApplication::translate("practiceClass", "Rec2_7", 0, QApplication::UnicodeUTF8));
        Rec2_10->setText(QApplication::translate("practiceClass", "Rec2_10", 0, QApplication::UnicodeUTF8));
        Rec2_8->setText(QApplication::translate("practiceClass", "Rec2_8", 0, QApplication::UnicodeUTF8));
        Rec2_6->setText(QApplication::translate("practiceClass", "Rec2_6", 0, QApplication::UnicodeUTF8));
        Rec2_4->setText(QApplication::translate("practiceClass", "Rec2_4", 0, QApplication::UnicodeUTF8));
        Rec2_2->setText(QApplication::translate("practiceClass", "Rec2_2", 0, QApplication::UnicodeUTF8));
        Rec2_12->setText(QApplication::translate("practiceClass", "Rec2_12", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("practiceClass", "5", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("practiceClass", "4", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("practiceClass", "2", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("practiceClass", "3", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("practiceClass", "1", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("practiceClass", "6", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("practiceClass", "7", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("practiceClass", "8", 0, QApplication::UnicodeUTF8));
        Square1_5->setText(QApplication::translate("practiceClass", "Sqaure1_3", 0, QApplication::UnicodeUTF8));
        Square1_6->setText(QApplication::translate("practiceClass", "Sqaure1_3", 0, QApplication::UnicodeUTF8));
        menu->setTitle(QApplication::translate("practiceClass", "\353\263\264\352\270\260", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class practiceClass: public Ui_practiceClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PRACTICE_H
